package com.airavat.panya.db.entities;

// default package
// Generated 13 Mar, 2016 10:19:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * BuyerProfile generated by hbm2java
 */
@Entity
@Table(name = "buyer_profile", schema = "public")
public class BuyerProfile implements java.io.Serializable {

	private long buyerId;
	private Users users;
	private String buyerPrimaryContact;
	private String buyerSecondaryContact;
	private String createdBy;
	private String deliveryAddress;
	private String modifiedBy;
	private String registeredShops;
	private Date createdDate;
	private Date modifiedDate;
	private Set<ShopFeedback> shopFeedbacks = new HashSet<ShopFeedback>(0);
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public BuyerProfile() {
	}

	public BuyerProfile(Users users, String buyerPrimaryContact,
			String buyerSecondaryContact, String createdBy,
			String deliveryAddress, String registeredShops, Date createdDate) {
		this.users = users;
		this.buyerPrimaryContact = buyerPrimaryContact;
		this.buyerSecondaryContact = buyerSecondaryContact;
		this.createdBy = createdBy;
		this.deliveryAddress = deliveryAddress;
		this.registeredShops = registeredShops;
		this.createdDate = createdDate;
	}

	public BuyerProfile(Users users, String buyerPrimaryContact,
			String buyerSecondaryContact, String createdBy,
			String deliveryAddress, String modifiedBy, String registeredShops,
			Date createdDate, Date modifiedDate,
			Set<ShopFeedback> shopFeedbacks, Set<Orders> orderses) {
		this.users = users;
		this.buyerPrimaryContact = buyerPrimaryContact;
		this.buyerSecondaryContact = buyerSecondaryContact;
		this.createdBy = createdBy;
		this.deliveryAddress = deliveryAddress;
		this.modifiedBy = modifiedBy;
		this.registeredShops = registeredShops;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.shopFeedbacks = shopFeedbacks;
		this.orderses = orderses;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "users"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "buyer_id", unique = true, nullable = false)
	public long getBuyerId() {
		return this.buyerId;
	}

	public void setBuyerId(long buyerId) {
		this.buyerId = buyerId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "buyer_primary_contact", nullable = false, length = 10)
	public String getBuyerPrimaryContact() {
		return this.buyerPrimaryContact;
	}

	public void setBuyerPrimaryContact(String buyerPrimaryContact) {
		this.buyerPrimaryContact = buyerPrimaryContact;
	}

	@Column(name = "buyer_secondary_contact", nullable = false, length = 10)
	public String getBuyerSecondaryContact() {
		return this.buyerSecondaryContact;
	}

	public void setBuyerSecondaryContact(String buyerSecondaryContact) {
		this.buyerSecondaryContact = buyerSecondaryContact;
	}

	@Column(name = "created_by", nullable = false, length = 32)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "delivery_address", nullable = false, length = 256)
	public String getDeliveryAddress() {
		return this.deliveryAddress;
	}

	public void setDeliveryAddress(String deliveryAddress) {
		this.deliveryAddress = deliveryAddress;
	}

	@Column(name = "modified_by", length = 32)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "registered_shops", nullable = false, length = 1024)
	public String getRegisteredShops() {
		return this.registeredShops;
	}

	public void setRegisteredShops(String registeredShops) {
		this.registeredShops = registeredShops;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 29)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "buyerProfile")
	public Set<ShopFeedback> getShopFeedbacks() {
		return this.shopFeedbacks;
	}

	public void setShopFeedbacks(Set<ShopFeedback> shopFeedbacks) {
		this.shopFeedbacks = shopFeedbacks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "buyerProfile")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
