package com.airavat.panya.db.entities;

// default package
// Generated 13 Mar, 2016 12:07:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BuyerProfile generated by hbm2java
 */
@Entity
@Table(name = "buyer_profile", schema = "public")
public class BuyerProfile implements java.io.Serializable {

	private long buyerId;
	private String registeredShops;
	private String deliveryAddress;
	private String buyerPrimaryContact;
	private String buyerSecondaryContact;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;

	public BuyerProfile() {
	}

	public BuyerProfile(long buyerId, String registeredShops,
			String deliveryAddress, String buyerPrimaryContact,
			String buyerSecondaryContact, Date createdDate, String createdBy,
			Date modifiedDate) {
		this.buyerId = buyerId;
		this.registeredShops = registeredShops;
		this.deliveryAddress = deliveryAddress;
		this.buyerPrimaryContact = buyerPrimaryContact;
		this.buyerSecondaryContact = buyerSecondaryContact;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
	}

	public BuyerProfile(long buyerId, String registeredShops,
			String deliveryAddress, String buyerPrimaryContact,
			String buyerSecondaryContact, Date createdDate, String createdBy,
			Date modifiedDate, String modifiedBy) {
		this.buyerId = buyerId;
		this.registeredShops = registeredShops;
		this.deliveryAddress = deliveryAddress;
		this.buyerPrimaryContact = buyerPrimaryContact;
		this.buyerSecondaryContact = buyerSecondaryContact;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
	}

	@Id
	@Column(name = "buyer_id", unique = true, nullable = false)
	public long getBuyerId() {
		return this.buyerId;
	}

	public void setBuyerId(long buyerId) {
		this.buyerId = buyerId;
	}

	@Column(name = "registered_shops", nullable = false, length = 1024)
	public String getRegisteredShops() {
		return this.registeredShops;
	}

	public void setRegisteredShops(String registeredShops) {
		this.registeredShops = registeredShops;
	}

	@Column(name = "delivery_address", nullable = false, length = 256)
	public String getDeliveryAddress() {
		return this.deliveryAddress;
	}

	public void setDeliveryAddress(String deliveryAddress) {
		this.deliveryAddress = deliveryAddress;
	}

	@Column(name = "buyer_primary_contact", nullable = false, length = 10)
	public String getBuyerPrimaryContact() {
		return this.buyerPrimaryContact;
	}

	public void setBuyerPrimaryContact(String buyerPrimaryContact) {
		this.buyerPrimaryContact = buyerPrimaryContact;
	}

	@Column(name = "buyer_secondary_contact", nullable = false, length = 10)
	public String getBuyerSecondaryContact() {
		return this.buyerSecondaryContact;
	}

	public void setBuyerSecondaryContact(String buyerSecondaryContact) {
		this.buyerSecondaryContact = buyerSecondaryContact;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "created_date", nullable = false, length = 21)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by", nullable = false, length = 32)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "modified_date", nullable = false, length = 21)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "modified_by", length = 32)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
