package com.airavat.panya.db.entities;

// default package
// Generated 13 Mar, 2016 12:07:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Discount generated by hbm2java
 */
@Entity
@Table(name = "discount", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "discount_name"))
public class Discount implements java.io.Serializable {

	private long discountId;
	private String discountName;
	private int discountType;
	private int discount;
	private Date discountStart;
	private Date discountExpiry;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;

	public Discount() {
	}

	public Discount(long discountId, String discountName, int discountType,
			int discount, Date discountStart, Date discountExpiry,
			Date createdDate, String createdBy, Date modifiedDate) {
		this.discountId = discountId;
		this.discountName = discountName;
		this.discountType = discountType;
		this.discount = discount;
		this.discountStart = discountStart;
		this.discountExpiry = discountExpiry;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
	}

	public Discount(long discountId, String discountName, int discountType,
			int discount, Date discountStart, Date discountExpiry,
			Date createdDate, String createdBy, Date modifiedDate,
			String modifiedBy) {
		this.discountId = discountId;
		this.discountName = discountName;
		this.discountType = discountType;
		this.discount = discount;
		this.discountStart = discountStart;
		this.discountExpiry = discountExpiry;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
	}

	@Id
	@Column(name = "discount_id", unique = true, nullable = false)
	public long getDiscountId() {
		return this.discountId;
	}

	public void setDiscountId(long discountId) {
		this.discountId = discountId;
	}

	@Column(name = "discount_name", unique = true, nullable = false, length = 32)
	public String getDiscountName() {
		return this.discountName;
	}

	public void setDiscountName(String discountName) {
		this.discountName = discountName;
	}

	@Column(name = "discount_type", nullable = false)
	public int getDiscountType() {
		return this.discountType;
	}

	public void setDiscountType(int discountType) {
		this.discountType = discountType;
	}

	@Column(name = "discount", nullable = false)
	public int getDiscount() {
		return this.discount;
	}

	public void setDiscount(int discount) {
		this.discount = discount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "discount_start", nullable = false, length = 35)
	public Date getDiscountStart() {
		return this.discountStart;
	}

	public void setDiscountStart(Date discountStart) {
		this.discountStart = discountStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "discount_expiry", nullable = false, length = 35)
	public Date getDiscountExpiry() {
		return this.discountExpiry;
	}

	public void setDiscountExpiry(Date discountExpiry) {
		this.discountExpiry = discountExpiry;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "created_date", nullable = false, length = 21)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by", nullable = false, length = 32)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "modified_date", nullable = false, length = 21)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "modified_by", length = 32)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
