package com.airavat.panya.db.entities;

// default package
// Generated 13 Mar, 2016 10:19:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.airavat.panya.model.IDiscount;

/**
 * Discount generated by hbm2java
 */
@Entity
@Table(name = "discount", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "discount_name"))
public class Discount implements java.io.Serializable, IDiscount {

	private long discountId;
	private int discount;
	private Date discountExpiry;
	private String discountName;
	private Date discountStart;
	private int discountType;
	private String createdBy;
	private String modifiedBy;
	private Date createdDate;
	private Date modifiedDate;
	private Set<Item> items = new HashSet<Item>(0);

	public Discount() {
	}

	public Discount(long discountId, int discount, Date discountExpiry,
			String discountName, Date discountStart, int discountType,
			String createdBy, Date createdDate) {
		this.discountId = discountId;
		this.discount = discount;
		this.discountExpiry = discountExpiry;
		this.discountName = discountName;
		this.discountStart = discountStart;
		this.discountType = discountType;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public Discount(long discountId, int discount, Date discountExpiry,
			String discountName, Date discountStart, int discountType,
			String createdBy, String modifiedBy, Date createdDate,
			Date modifiedDate, Set<Item> items) {
		this.discountId = discountId;
		this.discount = discount;
		this.discountExpiry = discountExpiry;
		this.discountName = discountName;
		this.discountStart = discountStart;
		this.discountType = discountType;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.items = items;
	}

	@Id
	@Column(name = "discount_id", unique = true, nullable = false)
	public long getDiscountId() {
		return this.discountId;
	}

	public void setDiscountId(long discountId) {
		this.discountId = discountId;
	}

	@Column(name = "discount", nullable = false)
	public int getDiscount() {
		return this.discount;
	}

	public void setDiscount(int discount) {
		this.discount = discount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "discount_expiry", nullable = false, length = 29)
	public Date getDiscountExpiry() {
		return this.discountExpiry;
	}

	public void setDiscountExpiry(Date discountExpiry) {
		this.discountExpiry = discountExpiry;
	}

	@Column(name = "discount_name", unique = true, nullable = false, length = 32)
	public String getDiscountName() {
		return this.discountName;
	}

	public void setDiscountName(String discountName) {
		this.discountName = discountName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "discount_start", nullable = false, length = 29)
	public Date getDiscountStart() {
		return this.discountStart;
	}

	public void setDiscountStart(Date discountStart) {
		this.discountStart = discountStart;
	}

	@Column(name = "discount_type", nullable = false)
	public int getDiscountType() {
		return this.discountType;
	}

	public void setDiscountType(int discountType) {
		this.discountType = discountType;
	}

	@Column(name = "created_by", nullable = false, length = 32)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "modified_by", length = 32)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 29)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discount")
	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

}
