package com.airavat.panya.db.entities;

// default package
// Generated 13 Mar, 2016 10:19:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.airavat.panya.model.IItem;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", schema = "public")
public class Item implements java.io.Serializable, IItem {

	private ItemId id;
	private Discount discount;
	private ShopkeeperProfile shopkeeperProfile;
	private String createdBy;
	private String itemBrand;
	private String itemDesc;
	private String itemName;
	private int itemPrice;
	private String itemUnit;
	private String modifiedBy;
	private Date createdDate;
	private Date modifiedDate;
	private Set<Cart> carts = new HashSet<Cart>(0);

	public Item() {
	}

	public Item(ItemId id, ShopkeeperProfile shopkeeperProfile,
			String createdBy, String itemName, int itemPrice, Date createdDate) {
		this.id = id;
		this.shopkeeperProfile = shopkeeperProfile;
		this.createdBy = createdBy;
		this.itemName = itemName;
		this.itemPrice = itemPrice;
		this.createdDate = createdDate;
	}

	public Item(ItemId id, Discount discount,
			ShopkeeperProfile shopkeeperProfile, String createdBy,
			String itemBrand, String itemDesc, String itemName, int itemPrice,
			String itemUnit, String modifiedBy, Date createdDate,
			Date modifiedDate, Set<Cart> carts) {
		this.id = id;
		this.discount = discount;
		this.shopkeeperProfile = shopkeeperProfile;
		this.createdBy = createdBy;
		this.itemBrand = itemBrand;
		this.itemDesc = itemDesc;
		this.itemName = itemName;
		this.itemPrice = itemPrice;
		this.itemUnit = itemUnit;
		this.modifiedBy = modifiedBy;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.carts = carts;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "itemId", column = @Column(name = "item_id", nullable = false)),
			@AttributeOverride(name = "shopId", column = @Column(name = "shop_id", nullable = false)) })
	public ItemId getId() {
		return this.id;
	}

	public void setId(ItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "discount_id")
	public Discount getDiscount() {
		return this.discount;
	}

	public void setDiscount(Discount discount) {
		this.discount = discount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shop_id", nullable = false, insertable = false, updatable = false)
	public ShopkeeperProfile getShopkeeperProfile() {
		return this.shopkeeperProfile;
	}

	public void setShopkeeperProfile(ShopkeeperProfile shopkeeperProfile) {
		this.shopkeeperProfile = shopkeeperProfile;
	}

	@Column(name = "created_by", nullable = false, length = 32)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "item_brand", length = 32)
	public String getItemBrand() {
		return this.itemBrand;
	}

	public void setItemBrand(String itemBrand) {
		this.itemBrand = itemBrand;
	}

	@Column(name = "item_desc", length = 64)
	public String getItemDesc() {
		return this.itemDesc;
	}

	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	@Column(name = "item_name", nullable = false, length = 32)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "item_price", nullable = false)
	public int getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(int itemPrice) {
		this.itemPrice = itemPrice;
	}

	@Column(name = "item_unit", length = 16)
	public String getItemUnit() {
		return this.itemUnit;
	}

	public void setItemUnit(String itemUnit) {
		this.itemUnit = itemUnit;
	}

	@Column(name = "modified_by", length = 32)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 29)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}

}
