package com.airavat.panya.db.entities;

// default package
// Generated 13 Mar, 2016 12:07:23 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderItemId generated by hbm2java
 */
@Embeddable
public class OrderItemId implements java.io.Serializable {

	private long oderId;
	private long itemId;

	public OrderItemId() {
	}

	public OrderItemId(long oderId, long itemId) {
		this.oderId = oderId;
		this.itemId = itemId;
	}

	@Column(name = "oder_id", nullable = false)
	public long getOderId() {
		return this.oderId;
	}

	public void setOderId(long oderId) {
		this.oderId = oderId;
	}

	@Column(name = "item_id", nullable = false)
	public long getItemId() {
		return this.itemId;
	}

	public void setItemId(long itemId) {
		this.itemId = itemId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderItemId))
			return false;
		OrderItemId castOther = (OrderItemId) other;

		return (this.getOderId() == castOther.getOderId())
				&& (this.getItemId() == castOther.getItemId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getOderId();
		result = 37 * result + (int) this.getItemId();
		return result;
	}

}
