package com.airavat.panya.db.entities;

// default package
// Generated 13 Mar, 2016 12:07:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", schema = "public")
public class Order implements java.io.Serializable {

	private long orderId;
	private long shopId;
	private long buyerId;
	private long totalPrice;
	private String oderStatus;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;

	public Order() {
	}

	public Order(long orderId, long shopId, long buyerId, long totalPrice,
			String oderStatus, Date createdDate, String createdBy,
			Date modifiedDate) {
		this.orderId = orderId;
		this.shopId = shopId;
		this.buyerId = buyerId;
		this.totalPrice = totalPrice;
		this.oderStatus = oderStatus;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
	}

	public Order(long orderId, long shopId, long buyerId, long totalPrice,
			String oderStatus, Date createdDate, String createdBy,
			Date modifiedDate, String modifiedBy) {
		this.orderId = orderId;
		this.shopId = shopId;
		this.buyerId = buyerId;
		this.totalPrice = totalPrice;
		this.oderStatus = oderStatus;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
	}

	@Id
	@Column(name = "order_id", unique = true, nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "shop_id", nullable = false)
	public long getShopId() {
		return this.shopId;
	}

	public void setShopId(long shopId) {
		this.shopId = shopId;
	}

	@Column(name = "buyer_id", nullable = false)
	public long getBuyerId() {
		return this.buyerId;
	}

	public void setBuyerId(long buyerId) {
		this.buyerId = buyerId;
	}

	@Column(name = "total_price", nullable = false)
	public long getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(long totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "oder_status", nullable = false, length = 32)
	public String getOderStatus() {
		return this.oderStatus;
	}

	public void setOderStatus(String oderStatus) {
		this.oderStatus = oderStatus;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "created_date", nullable = false, length = 21)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by", nullable = false, length = 32)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "modified_date", nullable = false, length = 21)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "modified_by", length = 32)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
