package com.airavat.panya.db.entities;

// default package
// Generated 13 Mar, 2016 12:07:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShopkeeperProfile generated by hbm2java
 */
@Entity
@Table(name = "shopkeeper_profile", schema = "public")
public class ShopkeeperProfile implements java.io.Serializable {

	private long shopId;
	private String shopAddress;
	private String shopCity;
	private String shopState;
	private String shopPrimaryContact;
	private String shopSecondaryContact;
	private Double shopCoordinatesLat;
	private Double shopCoordinatesLong;
	private String shopDesc;
	private String shopImage;
	private String shopPan;
	private String shopTin;
	private Date shopOpenTime;
	private Date shopCloseTime;
	private String shopProductTags;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;

	public ShopkeeperProfile() {
	}

	public ShopkeeperProfile(long shopId, String shopAddress, String shopCity,
			String shopState, String shopPrimaryContact, Date createdDate,
			String createdBy, Date modifiedDate) {
		this.shopId = shopId;
		this.shopAddress = shopAddress;
		this.shopCity = shopCity;
		this.shopState = shopState;
		this.shopPrimaryContact = shopPrimaryContact;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
	}

	public ShopkeeperProfile(long shopId, String shopAddress, String shopCity,
			String shopState, String shopPrimaryContact,
			String shopSecondaryContact, Double shopCoordinatesLat,
			Double shopCoordinatesLong, String shopDesc, String shopImage,
			String shopPan, String shopTin, Date shopOpenTime,
			Date shopCloseTime, String shopProductTags, Date createdDate,
			String createdBy, Date modifiedDate, String modifiedBy) {
		this.shopId = shopId;
		this.shopAddress = shopAddress;
		this.shopCity = shopCity;
		this.shopState = shopState;
		this.shopPrimaryContact = shopPrimaryContact;
		this.shopSecondaryContact = shopSecondaryContact;
		this.shopCoordinatesLat = shopCoordinatesLat;
		this.shopCoordinatesLong = shopCoordinatesLong;
		this.shopDesc = shopDesc;
		this.shopImage = shopImage;
		this.shopPan = shopPan;
		this.shopTin = shopTin;
		this.shopOpenTime = shopOpenTime;
		this.shopCloseTime = shopCloseTime;
		this.shopProductTags = shopProductTags;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
	}

	@Id
	@Column(name = "shop_id", unique = true, nullable = false)
	public long getShopId() {
		return this.shopId;
	}

	public void setShopId(long shopId) {
		this.shopId = shopId;
	}

	@Column(name = "shop_address", nullable = false, length = 256)
	public String getShopAddress() {
		return this.shopAddress;
	}

	public void setShopAddress(String shopAddress) {
		this.shopAddress = shopAddress;
	}

	@Column(name = "shop_city", nullable = false, length = 32)
	public String getShopCity() {
		return this.shopCity;
	}

	public void setShopCity(String shopCity) {
		this.shopCity = shopCity;
	}

	@Column(name = "shop_state", nullable = false, length = 32)
	public String getShopState() {
		return this.shopState;
	}

	public void setShopState(String shopState) {
		this.shopState = shopState;
	}

	@Column(name = "shop_primary_contact", nullable = false, length = 10)
	public String getShopPrimaryContact() {
		return this.shopPrimaryContact;
	}

	public void setShopPrimaryContact(String shopPrimaryContact) {
		this.shopPrimaryContact = shopPrimaryContact;
	}

	@Column(name = "shop_secondary_contact", length = 10)
	public String getShopSecondaryContact() {
		return this.shopSecondaryContact;
	}

	public void setShopSecondaryContact(String shopSecondaryContact) {
		this.shopSecondaryContact = shopSecondaryContact;
	}

	@Column(name = "shop_coordinates_lat", precision = 17, scale = 17)
	public Double getShopCoordinatesLat() {
		return this.shopCoordinatesLat;
	}

	public void setShopCoordinatesLat(Double shopCoordinatesLat) {
		this.shopCoordinatesLat = shopCoordinatesLat;
	}

	@Column(name = "shop_coordinates_long", precision = 17, scale = 17)
	public Double getShopCoordinatesLong() {
		return this.shopCoordinatesLong;
	}

	public void setShopCoordinatesLong(Double shopCoordinatesLong) {
		this.shopCoordinatesLong = shopCoordinatesLong;
	}

	@Column(name = "shop_desc", length = 1024)
	public String getShopDesc() {
		return this.shopDesc;
	}

	public void setShopDesc(String shopDesc) {
		this.shopDesc = shopDesc;
	}

	@Column(name = "shop_image", length = 32)
	public String getShopImage() {
		return this.shopImage;
	}

	public void setShopImage(String shopImage) {
		this.shopImage = shopImage;
	}

	@Column(name = "shop_pan", length = 32)
	public String getShopPan() {
		return this.shopPan;
	}

	public void setShopPan(String shopPan) {
		this.shopPan = shopPan;
	}

	@Column(name = "shop_tin", length = 32)
	public String getShopTin() {
		return this.shopTin;
	}

	public void setShopTin(String shopTin) {
		this.shopTin = shopTin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "shop_open_time", length = 29)
	public Date getShopOpenTime() {
		return this.shopOpenTime;
	}

	public void setShopOpenTime(Date shopOpenTime) {
		this.shopOpenTime = shopOpenTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "shop_close_time", length = 29)
	public Date getShopCloseTime() {
		return this.shopCloseTime;
	}

	public void setShopCloseTime(Date shopCloseTime) {
		this.shopCloseTime = shopCloseTime;
	}

	@Column(name = "shop_product_tags", length = 1024)
	public String getShopProductTags() {
		return this.shopProductTags;
	}

	public void setShopProductTags(String shopProductTags) {
		this.shopProductTags = shopProductTags;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "created_date", nullable = false, length = 21)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by", nullable = false, length = 32)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "modified_date", nullable = false, length = 21)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "modified_by", length = 32)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
