package com.airavat.panya.db.entities;

// default package
// Generated 13 Mar, 2016 10:19:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ShopkeeperProfile generated by hbm2java
 */
@Entity
@Table(name = "shopkeeper_profile", schema = "public")
public class ShopkeeperProfile implements java.io.Serializable {

	private long shopId;
	private Users users;
	private String createdBy;
	private String modifiedBy;
	private String shopAddress;
	private String shopCity;
	private Date shopCloseTime;
	private Double shopCoordinatesLat;
	private Double shopCoordinatesLong;
	private String shopDesc;
	private String shopImage;
	private Date shopOpenTime;
	private String shopPan;
	private String shopPrimaryContact;
	private String shopProductTags;
	private String shopSecondaryContact;
	private String shopState;
	private String shopTin;
	private Date createdDate;
	private Date modifiedDate;
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<Item> items = new HashSet<Item>(0);
	private Set<ShopFeedback> shopFeedbacks = new HashSet<ShopFeedback>(0);

	public ShopkeeperProfile() {
	}

	public ShopkeeperProfile(Users users, String createdBy, String shopAddress,
			String shopCity, String shopPrimaryContact, String shopState,
			Date createdDate) {
		this.users = users;
		this.createdBy = createdBy;
		this.shopAddress = shopAddress;
		this.shopCity = shopCity;
		this.shopPrimaryContact = shopPrimaryContact;
		this.shopState = shopState;
		this.createdDate = createdDate;
	}

	public ShopkeeperProfile(Users users, String createdBy, String modifiedBy,
			String shopAddress, String shopCity, Date shopCloseTime,
			Double shopCoordinatesLat, Double shopCoordinatesLong,
			String shopDesc, String shopImage, Date shopOpenTime,
			String shopPan, String shopPrimaryContact, String shopProductTags,
			String shopSecondaryContact, String shopState, String shopTin,
			Date createdDate, Date modifiedDate, Set<Orders> orderses,
			Set<Item> items, Set<ShopFeedback> shopFeedbacks) {
		this.users = users;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.shopAddress = shopAddress;
		this.shopCity = shopCity;
		this.shopCloseTime = shopCloseTime;
		this.shopCoordinatesLat = shopCoordinatesLat;
		this.shopCoordinatesLong = shopCoordinatesLong;
		this.shopDesc = shopDesc;
		this.shopImage = shopImage;
		this.shopOpenTime = shopOpenTime;
		this.shopPan = shopPan;
		this.shopPrimaryContact = shopPrimaryContact;
		this.shopProductTags = shopProductTags;
		this.shopSecondaryContact = shopSecondaryContact;
		this.shopState = shopState;
		this.shopTin = shopTin;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.orderses = orderses;
		this.items = items;
		this.shopFeedbacks = shopFeedbacks;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "users"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "shop_id", unique = true, nullable = false)
	public long getShopId() {
		return this.shopId;
	}

	public void setShopId(long shopId) {
		this.shopId = shopId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "created_by", nullable = false, length = 32)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "modified_by", length = 32)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "shop_address", nullable = false, length = 256)
	public String getShopAddress() {
		return this.shopAddress;
	}

	public void setShopAddress(String shopAddress) {
		this.shopAddress = shopAddress;
	}

	@Column(name = "shop_city", nullable = false, length = 32)
	public String getShopCity() {
		return this.shopCity;
	}

	public void setShopCity(String shopCity) {
		this.shopCity = shopCity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "shop_close_time", length = 29)
	public Date getShopCloseTime() {
		return this.shopCloseTime;
	}

	public void setShopCloseTime(Date shopCloseTime) {
		this.shopCloseTime = shopCloseTime;
	}

	@Column(name = "shop_coordinates_lat", precision = 17, scale = 17)
	public Double getShopCoordinatesLat() {
		return this.shopCoordinatesLat;
	}

	public void setShopCoordinatesLat(Double shopCoordinatesLat) {
		this.shopCoordinatesLat = shopCoordinatesLat;
	}

	@Column(name = "shop_coordinates_long", precision = 17, scale = 17)
	public Double getShopCoordinatesLong() {
		return this.shopCoordinatesLong;
	}

	public void setShopCoordinatesLong(Double shopCoordinatesLong) {
		this.shopCoordinatesLong = shopCoordinatesLong;
	}

	@Column(name = "shop_desc", length = 1024)
	public String getShopDesc() {
		return this.shopDesc;
	}

	public void setShopDesc(String shopDesc) {
		this.shopDesc = shopDesc;
	}

	@Column(name = "shop_image", length = 32)
	public String getShopImage() {
		return this.shopImage;
	}

	public void setShopImage(String shopImage) {
		this.shopImage = shopImage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "shop_open_time", length = 29)
	public Date getShopOpenTime() {
		return this.shopOpenTime;
	}

	public void setShopOpenTime(Date shopOpenTime) {
		this.shopOpenTime = shopOpenTime;
	}

	@Column(name = "shop_pan", length = 32)
	public String getShopPan() {
		return this.shopPan;
	}

	public void setShopPan(String shopPan) {
		this.shopPan = shopPan;
	}

	@Column(name = "shop_primary_contact", nullable = false, length = 10)
	public String getShopPrimaryContact() {
		return this.shopPrimaryContact;
	}

	public void setShopPrimaryContact(String shopPrimaryContact) {
		this.shopPrimaryContact = shopPrimaryContact;
	}

	@Column(name = "shop_product_tags", length = 1024)
	public String getShopProductTags() {
		return this.shopProductTags;
	}

	public void setShopProductTags(String shopProductTags) {
		this.shopProductTags = shopProductTags;
	}

	@Column(name = "shop_secondary_contact", length = 10)
	public String getShopSecondaryContact() {
		return this.shopSecondaryContact;
	}

	public void setShopSecondaryContact(String shopSecondaryContact) {
		this.shopSecondaryContact = shopSecondaryContact;
	}

	@Column(name = "shop_state", nullable = false, length = 32)
	public String getShopState() {
		return this.shopState;
	}

	public void setShopState(String shopState) {
		this.shopState = shopState;
	}

	@Column(name = "shop_tin", length = 32)
	public String getShopTin() {
		return this.shopTin;
	}

	public void setShopTin(String shopTin) {
		this.shopTin = shopTin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 29)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopkeeperProfile")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopkeeperProfile")
	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopkeeperProfile")
	public Set<ShopFeedback> getShopFeedbacks() {
		return this.shopFeedbacks;
	}

	public void setShopFeedbacks(Set<ShopFeedback> shopFeedbacks) {
		this.shopFeedbacks = shopFeedbacks;
	}

}
