package com.airavat.panya.db.entities;

// default package
// Generated 13 Mar, 2016 10:19:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.airavat.panya.model.IShopFeedback;

/**
 * ShopFeedback generated by hbm2java
 */
@Entity
@Table(name = "shop_feedback", schema = "public")
public class ShopFeedback implements java.io.Serializable, IShopFeedback {

	private ShopFeedbackId id;
	private BuyerProfile buyerProfile;
	private ShopkeeperProfile shopkeeperProfile;
	private String createdBy;
	private String modifiedBy;
	private String shopComments;
	private int shopRatings;
	private Date createdDate;
	private Date modifiedDate;

	public ShopFeedback() {
	}

	public ShopFeedback(ShopFeedbackId id, BuyerProfile buyerProfile,
			ShopkeeperProfile shopkeeperProfile, String createdBy,
			int shopRatings, Date createdDate) {
		this.id = id;
		this.buyerProfile = buyerProfile;
		this.shopkeeperProfile = shopkeeperProfile;
		this.createdBy = createdBy;
		this.shopRatings = shopRatings;
		this.createdDate = createdDate;
	}

	public ShopFeedback(ShopFeedbackId id, BuyerProfile buyerProfile,
			ShopkeeperProfile shopkeeperProfile, String createdBy,
			String modifiedBy, String shopComments, int shopRatings,
			Date createdDate, Date modifiedDate) {
		this.id = id;
		this.buyerProfile = buyerProfile;
		this.shopkeeperProfile = shopkeeperProfile;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.shopComments = shopComments;
		this.shopRatings = shopRatings;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "buyerId", column = @Column(name = "buyer_id", nullable = false)),
			@AttributeOverride(name = "shopId", column = @Column(name = "shop_id", nullable = false)) })
	public ShopFeedbackId getId() {
		return this.id;
	}

	public void setId(ShopFeedbackId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "buyer_id", nullable = false, insertable = false, updatable = false)
	public BuyerProfile getBuyerProfile() {
		return this.buyerProfile;
	}

	public void setBuyerProfile(BuyerProfile buyerProfile) {
		this.buyerProfile = buyerProfile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shop_id", nullable = false, insertable = false, updatable = false)
	public ShopkeeperProfile getShopkeeperProfile() {
		return this.shopkeeperProfile;
	}

	public void setShopkeeperProfile(ShopkeeperProfile shopkeeperProfile) {
		this.shopkeeperProfile = shopkeeperProfile;
	}

	@Column(name = "created_by", nullable = false, length = 32)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "modified_by", length = 32)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "shop_comments", length = 1024)
	public String getShopComments() {
		return this.shopComments;
	}

	public void setShopComments(String shopComments) {
		this.shopComments = shopComments;
	}

	@Column(name = "shop_ratings", nullable = false)
	public int getShopRatings() {
		return this.shopRatings;
	}

	public void setShopRatings(int shopRatings) {
		this.shopRatings = shopRatings;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 29)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
