package com.airavat.panya.db.entities;

// default package
// Generated 13 Mar, 2016 10:19:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.airavat.panya.model.IUser;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class Users implements java.io.Serializable, IUser {

	private long userId;
	private String createdBy;
	private String firstName;
	private String lastName;
	private String mailId;
	private String modifiedBy;
	private String password;
	private int type;
	private String username;
	private boolean enabled;
	private Date createdDate;
	private Date modifiedDate;
	private Set<Authorities> authoritieses = new HashSet<Authorities>(0);
	private BuyerProfile buyerProfile;
	private ShopkeeperProfile shopkeeperProfile;

	public Users() {
	}

	public Users(long userId, String createdBy, String firstName,
			String mailId, String password, int type, String username,
			boolean enabled, Date createdDate) {
		this.userId = userId;
		this.createdBy = createdBy;
		this.firstName = firstName;
		this.mailId = mailId;
		this.password = password;
		this.type = type;
		this.username = username;
		this.enabled = enabled;
		this.createdDate = createdDate;
	}

	public Users(long userId, String createdBy, String firstName,
			String lastName, String mailId, String modifiedBy, String password,
			int type, String username, boolean enabled, Date createdDate,
			Date modifiedDate, Set<Authorities> authoritieses,
			BuyerProfile buyerProfile, ShopkeeperProfile shopkeeperProfile) {
		this.userId = userId;
		this.createdBy = createdBy;
		this.firstName = firstName;
		this.lastName = lastName;
		this.mailId = mailId;
		this.modifiedBy = modifiedBy;
		this.password = password;
		this.type = type;
		this.username = username;
		this.enabled = enabled;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.authoritieses = authoritieses;
		this.buyerProfile = buyerProfile;
		this.shopkeeperProfile = shopkeeperProfile;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "created_by", nullable = false, length = 32)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "first_name", nullable = false, length = 64)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 64)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "mail_id", nullable = false, length = 64)
	public String getMailId() {
		return this.mailId;
	}

	public void setMailId(String mailId) {
		this.mailId = mailId;
	}

	@Column(name = "modified_by", length = 32)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "password", nullable = false, length = 64)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "username", unique = true, nullable = false, length = 32)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 29)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Authorities> getAuthoritieses() {
		return this.authoritieses;
	}

	public void setAuthoritieses(Set<Authorities> authoritieses) {
		this.authoritieses = authoritieses;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "users")
	public BuyerProfile getBuyerProfile() {
		return this.buyerProfile;
	}

	public void setBuyerProfile(BuyerProfile buyerProfile) {
		this.buyerProfile = buyerProfile;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "users")
	public ShopkeeperProfile getShopkeeperProfile() {
		return this.shopkeeperProfile;
	}

	public void setShopkeeperProfile(ShopkeeperProfile shopkeeperProfile) {
		this.shopkeeperProfile = shopkeeperProfile;
	}

}
